{
 "title": "Blog Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CloudflareD Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_total_requests[1m])"
    }
   ]
  },
  {
   "title": "NGINX Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{namespace=\"jekyllpreviewv2\"}[5m])"
    }
   ]
  },
  {
   "title": "NGINX Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_connections_active" },
    { "expr": "nginx_connections_reading" },
    { "expr": "nginx_connections_writing" }
   ]
  },
  {
   "title": "Webhook calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(previewd_webhook_totalops[5m])"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{namespace=\"jekyllpreviewv2\"}"
    }
   ]
  },
  {
   "title": "NGinx Requests/s instantaneous",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[40s])"
    }
   ]
  },
  {
   "title": "CloudflareD response codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_response_by_code"
    }
   ]
  }
 ]
}