namespace: monitoring
commonLabels:
    app: grafana
resources:
- grafana-deployment.yaml
- grafana-pvc.yaml
- grafana-service.yaml
- grafana-serviceaccount.yaml
- grafana-dashboardSources.yaml
- grafana-dashboardDatasources.yaml
- dashboard-traefik.yaml
- dashboard-longhorn.yaml
- dashboard-blog.yaml
- dashboard-certmanager.yaml
